name: Build and Publish to PyPI

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build wheels for Python ${{ matrix.python-version }} on ${{ matrix.os }} and publishes to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.13"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup UV Python package manager
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Set version based on tag
        run: uv version ${{github.ref_name}}

      - name: Build wheel
        run: uv build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-distributions
          path: dist/*
          if-no-files-found: error
          retention-days: 14

      - name: Publish to PyPI
        run: uv publish
