name: Checks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rust-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check formatting
        run: cargo fmt -- --check

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  python-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Setup UV Python package manager
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.13"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Run pytest tests
        run: uv run pytest
      
